id: P010738
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG16612
  title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེའི་རྒྱན་དང་རྒྱུད་བླ་རྩ་འགྲེལ།
  author: ''
  volumes:
    48a9eaadbaa14f4f917abe123de30d4d:
      image_group_id: I1KG16659
      title: ''
      volume_number: 1
      total_pages: 544
      base_file: v001.txt
