id: IB551F7FF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:27:14+00:00'
last_modified: '2022-06-08T17:10:15.930349+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16612
  title: ཐེག་པ་ཆེན་པོ་མདོ་སྡེའི་རྒྱན་དང་རྒྱུད་བླ་རྩ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    48F8:
      image_group_id: I1KG16659
      title: ''
      total_pages: 544
      order: 1
      base_file: 48F8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
